// dashstack(1)/src/app/pages/Dashboard.tsx
import {
  AreaChart, Area, XAxis, YAxis, CartesianGrid, Tooltip,
  ResponsiveContainer, BarChart, Bar,
} from "recharts";
import {
  Users, FileText, Euro, AlertTriangle, TrendingUp, TrendingDown,
  CheckCircle2, XCircle, Clock, Dumbbell, Wrench, BookOpen,
} from "lucide-react";
import { motion } from "motion/react";
import { Link } from "react-router";

const MONTHLY_REVENUE = [
  { month: "Apr", revenue: 28400, contracts: 580 },
  { month: "May", revenue: 31200, contracts: 601 },
  { month: "Jun", revenue: 29800, contracts: 595 },
  { month: "Jul", revenue: 33100, contracts: 618 },
  { month: "Aug", revenue: 35600, contracts: 629 },
  { month: "Sep", revenue: 34200, contracts: 623 },
  { month: "Oct", revenue: 36800, contracts: 638 },
  { month: "Nov", revenue: 35100, contracts: 630 },
  { month: "Dec", revenue: 37400, contracts: 644 },
  { month: "Jan", revenue: 36900, contracts: 641 },
  { month: "Feb", revenue: 37800, contracts: 648 },
  { month: "Mar", revenue: 38420, contracts: 651 },
];

const MEMBER_STATUS_DATA = [
  { label: "Active", value: 782, color: "#00B69B", bg: "bg-[#E0F8EA]" },
  { label: "Suspended", value: 65, color: "#FF9066", bg: "bg-[#FFF3D6]" },
  { label: "Anonymized", value: 12, color: "#A6A6A6", bg: "bg-[#F5F6FA]" },
];

const RECENT_ACCESS = [
  { memberName: "Jean Dupont", club: "Brussels", time: "11:45", result: "Granted" as const },
  { memberName: "Clara Morin", club: "Brussels", time: "11:07", result: "Denied" as const },
  { memberName: "Pierre Dumont", club: "Brussels", time: "10:22", result: "Denied" as const },
  { memberName: "Sophie Leroy", club: "Brussels", time: "10:05", result: "Granted" as const },
  { memberName: "Unknown", club: "Namur", time: "09:01", result: "Denied" as const },
];

const UPCOMING_SESSIONS = [
  { course: "Power Yoga", instructor: "M. Laurent", club: "Brussels", time: "14:00", capacity: 20, enrolled: 18 },
  { course: "HIIT Cardio", instructor: "R. Moreau", club: "Liège", time: "15:30", capacity: 15, enrolled: 15 },
  { course: "Pilates", instructor: "S. Dupuis", club: "Brussels", time: "17:00", capacity: 12, enrolled: 7 },
  { course: "Boxing", instructor: "K. Osei", club: "Namur", time: "18:30", capacity: 10, enrolled: 10 },
];

const EQUIPMENT_SUMMARY = [
  { label: "In Service", count: 142, color: "text-[#00B69B]", bg: "bg-[#E0F8EA]", icon: Dumbbell },
  { label: "Maintenance", count: 8, color: "text-[#FF9066]", bg: "bg-[#FFF3D6]", icon: Wrench },
  { label: "Broken", count: 3, color: "text-[#FF4747]", bg: "bg-[#FFF0F0]", icon: AlertTriangle },
];

const KPI_CARDS = [
  {
    label: "Active Members",
    value: "782",
    sub: "out of 859 total",
    trend: +5.2,
    trendLabel: "vs last month",
    icon: Users,
    accent: "#4880FF",
    bg: "bg-[#EBEBFF]",
    border: "border-[#4880FF]/10",
    link: "/members",
  },
  {
    label: "Active Contracts",
    value: "651",
    sub: "23 expiring soon",
    trend: +2.1,
    trendLabel: "vs last month",
    icon: FileText,
    accent: "#00B69B",
    bg: "bg-[#E0F8EA]",
    border: "border-[#00B69B]/10",
    link: "/contracts",
  },
  {
    label: "Revenue (March)",
    value: "38 420 €",
    sub: "from 651 invoices",
    trend: +6.2,
    trendLabel: "vs February",
    icon: Euro,
    accent: "#8B5CF6",
    bg: "bg-[#F3F0FF]",
    border: "border-[#8B5CF6]/10",
    link: "/billing/invoices",
  },
  {
    label: "Overdue Invoices",
    value: "18",
    sub: "2 847 € outstanding",
    trend: -3,
    trendLabel: "vs last week",
    icon: AlertTriangle,
    accent: "#FF4747",
    bg: "bg-[#FFF0F0]",
    border: "border-[#FF4747]/10",
    link: "/billing/invoices",
  },
];

export function Dashboard() {
  const totalMembers = MEMBER_STATUS_DATA.reduce((s, d) => s + d.value, 0);

  return (
    <div className="flex flex-col h-full overflow-y-auto bg-[#F5F6FA]">
      <div className="p-8 flex flex-col gap-7">
        {/* Header */}
        <div>
          <h1 className="text-2xl font-bold text-[#111827]">Dashboard</h1>
          <p className="text-sm text-[#6B7280] mt-0.5">Wednesday, 18 March 2026</p>
        </div>

        {/* KPI Cards */}
        <div className="grid grid-cols-2 xl:grid-cols-4 gap-5">
          {KPI_CARDS.map(({ label, value, sub, trend, trendLabel, icon: Icon, accent, bg, border, link }, i) => (
            <motion.div
              key={label}
              initial={{ opacity: 0, y: 20 }}
              animate={{ opacity: 1, y: 0 }}
              transition={{ delay: i * 0.07 }}
              className={`bg-white rounded-2xl p-5 shadow-sm border ${border} hover:shadow-md transition-shadow cursor-pointer`}
              onClick={() => window.location.href = link}
            >
              <div className="flex items-start justify-between mb-4">
                <div className={`w-11 h-11 rounded-xl ${bg} flex items-center justify-center shrink-0`}>
                  <Icon className="w-5 h-5" style={{ color: accent }} />
                </div>
                <span
                  className={`flex items-center gap-1 text-xs font-semibold ${trend >= 0 ? "text-[#00B69B]" : "text-[#FF4747]"}`}
                >
                  {trend >= 0 ? <TrendingUp className="w-3.5 h-3.5" /> : <TrendingDown className="w-3.5 h-3.5" />}
                  {Math.abs(trend)}%
                </span>
              </div>
              <p className="text-2xl font-black text-[#111827] leading-tight">{value}</p>
              <p className="text-[13px] font-semibold text-[#6B7280] mt-0.5">{label}</p>
              <p className="text-[11px] text-[#A6A6A6] mt-1">{sub} · {trendLabel}</p>
            </motion.div>
          ))}
        </div>

        {/* Revenue Chart + Member Status */}
        <div className="grid grid-cols-1 xl:grid-cols-[1fr_320px] gap-5">
          <motion.div
            initial={{ opacity: 0, y: 20 }}
            animate={{ opacity: 1, y: 0 }}
            transition={{ delay: 0.28 }}
            className="bg-white rounded-2xl p-6 shadow-sm border border-[#E0E0E0]"
          >
            <div className="flex items-center justify-between mb-5">
              <div>
                <h2 className="text-[17px] font-bold text-[#111827]">Monthly Revenue</h2>
                <p className="text-sm text-[#6B7280]">Last 12 months</p>
              </div>
              <div className="flex items-center gap-4 text-xs font-semibold">
                <span className="flex items-center gap-1.5 text-[#4880FF]">
                  <span className="w-3 h-1.5 rounded-full bg-[#4880FF] inline-block" /> Revenue (€)
                </span>
              </div>
            </div>
            <div className="h-[240px]">
              <ResponsiveContainer width="100%" height="100%">
                <AreaChart data={MONTHLY_REVENUE} margin={{ top: 5, right: 5, left: -15, bottom: 0 }}>
                  <defs>
                    <linearGradient id="revGrad" x1="0" y1="0" x2="0" y2="1">
                      <stop offset="5%" stopColor="#4880FF" stopOpacity={0.2} />
                      <stop offset="95%" stopColor="#4880FF" stopOpacity={0} />
                    </linearGradient>
                  </defs>
                  <CartesianGrid strokeDasharray="3 3" vertical={false} stroke="#F0F0F0" />
                  <XAxis dataKey="month" axisLine={false} tickLine={false} tick={{ fill: "#A6A6A6", fontSize: 11 }} dy={8} />
                  <YAxis axisLine={false} tickLine={false} tick={{ fill: "#A6A6A6", fontSize: 11 }} tickFormatter={(v) => `${(v / 1000).toFixed(0)}k`} />
                  <Tooltip
                    contentStyle={{ borderRadius: "12px", border: "none", boxShadow: "0 10px 40px rgba(0,0,0,0.1)", fontSize: 13 }}
                    formatter={(v: number) => [`${v.toLocaleString("fr-BE")} €`, "Revenue"]}
                  />
                  <Area type="monotone" dataKey="revenue" stroke="#4880FF" strokeWidth={3} fill="url(#revGrad)" dot={false} activeDot={{ r: 5, fill: "#4880FF" }} />
                </AreaChart>
              </ResponsiveContainer>
            </div>
          </motion.div>

          {/* Member status breakdown */}
          <motion.div
            initial={{ opacity: 0, y: 20 }}
            animate={{ opacity: 1, y: 0 }}
            transition={{ delay: 0.33 }}
            className="bg-white rounded-2xl p-6 shadow-sm border border-[#E0E0E0] flex flex-col"
          >
            <h2 className="text-[17px] font-bold text-[#111827] mb-1">Member Status</h2>
            <p className="text-sm text-[#6B7280] mb-5">{totalMembers} total members</p>

            {/* Simple radial progress ring */}
            <div className="flex items-center justify-center my-2">
              <div className="relative w-32 h-32">
                <svg className="w-full h-full -rotate-90" viewBox="0 0 120 120">
                  <circle cx="60" cy="60" r="50" fill="none" stroke="#F0F0F0" strokeWidth="14" />
                  <circle
                    cx="60" cy="60" r="50" fill="none" stroke="#00B69B" strokeWidth="14"
                    strokeDasharray={`${(782 / totalMembers) * 314} 314`} strokeLinecap="round"
                  />
                </svg>
                <div className="absolute inset-0 flex flex-col items-center justify-center">
                  <span className="text-xl font-black text-[#111827]">{Math.round((782 / totalMembers) * 100)}%</span>
                  <span className="text-[10px] text-[#6B7280] font-medium">Active</span>
                </div>
              </div>
            </div>

            <div className="flex flex-col gap-3 mt-4">
              {MEMBER_STATUS_DATA.map(({ label, value, color, bg }) => (
                <div key={label} className="flex items-center justify-between">
                  <div className="flex items-center gap-2.5">
                    <div className={`w-2.5 h-2.5 rounded-full`} style={{ backgroundColor: color }} />
                    <span className="text-sm font-medium text-[#505050]">{label}</span>
                  </div>
                  <div className="flex items-center gap-3">
                    <div className="w-24 h-1.5 bg-[#F0F0F0] rounded-full overflow-hidden">
                      <div className="h-full rounded-full" style={{ width: `${(value / totalMembers) * 100}%`, backgroundColor: color }} />
                    </div>
                    <span className="text-sm font-bold text-[#111827] w-8 text-right">{value}</span>
                  </div>
                </div>
              ))}
            </div>

            <Link to="/members" className="mt-5 text-center text-sm text-[#4880FF] font-semibold hover:underline">
              View all members →
            </Link>
          </motion.div>
        </div>

        {/* Bottom row */}
        <div className="grid grid-cols-1 xl:grid-cols-3 gap-5">
          {/* Recent Access Logs */}
          <motion.div
            initial={{ opacity: 0, y: 20 }}
            animate={{ opacity: 1, y: 0 }}
            transition={{ delay: 0.38 }}
            className="bg-white rounded-2xl shadow-sm border border-[#E0E0E0] overflow-hidden"
          >
            <div className="px-5 py-4 border-b border-[#F0F0F0] flex items-center justify-between">
              <h2 className="text-[15px] font-bold text-[#111827]">Recent Access</h2>
              <Link to="/access-control" className="text-xs text-[#4880FF] font-semibold hover:underline">View all</Link>
            </div>
            <div className="divide-y divide-[#F5F5F5]">
              {RECENT_ACCESS.map(({ memberName, club, time, result }, i) => (
                <div key={i} className="flex items-center justify-between px-5 py-3">
                  <div className="flex items-center gap-3 min-w-0">
                    {result === "Granted"
                      ? <CheckCircle2 className="w-4 h-4 text-[#00B69B] shrink-0" />
                      : <XCircle className="w-4 h-4 text-[#FF4747] shrink-0" />}
                    <div className="min-w-0">
                      <p className="text-sm font-semibold text-[#111827] truncate">{memberName}</p>
                      <p className="text-xs text-[#A6A6A6]">{club}</p>
                    </div>
                  </div>
                  <div className="flex items-center gap-1.5 text-xs text-[#A6A6A6] shrink-0">
                    <Clock className="w-3 h-3" /> {time}
                  </div>
                </div>
              ))}
            </div>
          </motion.div>

          {/* Upcoming Sessions */}
          <motion.div
            initial={{ opacity: 0, y: 20 }}
            animate={{ opacity: 1, y: 0 }}
            transition={{ delay: 0.43 }}
            className="bg-white rounded-2xl shadow-sm border border-[#E0E0E0] overflow-hidden"
          >
            <div className="px-5 py-4 border-b border-[#F0F0F0] flex items-center justify-between">
              <h2 className="text-[15px] font-bold text-[#111827]">Today's Sessions</h2>
              <Link to="/courses/schedule" className="text-xs text-[#4880FF] font-semibold hover:underline">Schedule</Link>
            </div>
            <div className="divide-y divide-[#F5F5F5]">
              {UPCOMING_SESSIONS.map(({ course, instructor, club, time, capacity, enrolled }, i) => {
                const full = enrolled >= capacity;
                const pct = Math.round((enrolled / capacity) * 100);
                return (
                  <div key={i} className="px-5 py-3">
                    <div className="flex items-start justify-between mb-1">
                      <div>
                        <p className="text-sm font-semibold text-[#111827]">{course}</p>
                        <p className="text-xs text-[#A6A6A6]">{instructor} · {club}</p>
                      </div>
                      <div className="flex items-center gap-1 text-xs text-[#6B7280] shrink-0 ml-3">
                        <Clock className="w-3 h-3" /> {time}
                      </div>
                    </div>
                    <div className="flex items-center gap-2 mt-1.5">
                      <div className="flex-1 h-1.5 bg-[#F0F0F0] rounded-full overflow-hidden">
                        <div
                          className={`h-full rounded-full ${full ? "bg-[#FF4747]" : "bg-[#4880FF]"}`}
                          style={{ width: `${pct}%` }}
                        />
                      </div>
                      <span className={`text-[11px] font-bold ${full ? "text-[#FF4747]" : "text-[#6B7280]"}`}>
                        {enrolled}/{capacity}
                      </span>
                    </div>
                  </div>
                );
              })}
            </div>
          </motion.div>

          {/* Equipment Summary + Contract Bar Chart */}
          <motion.div
            initial={{ opacity: 0, y: 20 }}
            animate={{ opacity: 1, y: 0 }}
            transition={{ delay: 0.48 }}
            className="bg-white rounded-2xl shadow-sm border border-[#E0E0E0] overflow-hidden flex flex-col"
          >
            <div className="px-5 py-4 border-b border-[#F0F0F0] flex items-center justify-between">
              <h2 className="text-[15px] font-bold text-[#111827]">Equipment</h2>
              <Link to="/equipment" className="text-xs text-[#4880FF] font-semibold hover:underline">View all</Link>
            </div>

            <div className="flex flex-col gap-3 p-5">
              {EQUIPMENT_SUMMARY.map(({ label, count, color, bg, icon: Icon }) => (
                <div key={label} className="flex items-center gap-3">
                  <div className={`w-9 h-9 rounded-xl ${bg} flex items-center justify-center shrink-0`}>
                    <Icon className={`w-4 h-4 ${color}`} />
                  </div>
                  <div className="flex-1">
                    <p className="text-sm font-medium text-[#505050]">{label}</p>
                  </div>
                  <span className={`text-lg font-black ${color}`}>{count}</span>
                </div>
              ))}
            </div>

            <div className="px-5 pb-5 pt-2 border-t border-[#F5F5F5]">
              <p className="text-[13px] font-bold text-[#111827] mb-3">Contracts / Month</p>
              <div className="h-[100px]">
                <ResponsiveContainer width="100%" height="100%">
                  <BarChart data={MONTHLY_REVENUE.slice(-6)} margin={{ top: 0, right: 0, left: -30, bottom: 0 }} barSize={8}>
                    <XAxis dataKey="month" axisLine={false} tickLine={false} tick={{ fill: "#A6A6A6", fontSize: 10 }} />
                    <YAxis axisLine={false} tickLine={false} tick={{ fill: "#A6A6A6", fontSize: 10 }} domain={["dataMin - 10", "dataMax + 5"]} />
                    <Tooltip
                      contentStyle={{ borderRadius: "10px", border: "none", boxShadow: "0 4px 20px rgba(0,0,0,0.1)", fontSize: 12 }}
                      formatter={(v: number) => [v, "Contracts"]}
                    />
                    <Bar dataKey="contracts" fill="#4880FF" radius={[4, 4, 0, 0]} />
                  </BarChart>
                </ResponsiveContainer>
              </div>
            </div>
          </motion.div>
        </div>
      </div>
    </div>
  );
}

// frontend/src/app/pages/dashboard/dashboard.component.ts
import { DecimalPipe } from '@angular/common';
import { Component } from '@angular/core';
import { RouterLink } from '@angular/router';
import { NgApexchartsModule } from 'ng-apexcharts';
import { LucideAngularModule, Users, FileText, AlertTriangle, TrendingUp, TrendingDown, CheckCircle, XCircle, Clock, Dumbbell, Wrench } from 'lucide-angular';

const MONTHLY_REVENUE = [
  { month: 'Apr', revenue: 28400, contracts: 580 }, { month: 'May', revenue: 31200, contracts: 601 },
  { month: 'Jun', revenue: 29800, contracts: 595 }, { month: 'Jul', revenue: 33100, contracts: 618 },
  { month: 'Aug', revenue: 35600, contracts: 629 }, { month: 'Sep', revenue: 34200, contracts: 623 },
  { month: 'Oct', revenue: 36800, contracts: 638 }, { month: 'Nov', revenue: 35100, contracts: 630 },
  { month: 'Dec', revenue: 37400, contracts: 644 }, { month: 'Jan', revenue: 36900, contracts: 641 },
  { month: 'Feb', revenue: 37800, contracts: 648 }, { month: 'Mar', revenue: 38420, contracts: 651 },
];

const MEMBER_STATUS_DATA = [
  { label: 'Active',     value: 782, color: '#00B69B' },
  { label: 'Suspended',  value: 65,  color: '#FF9066' },
  { label: 'Anonymized', value: 12,  color: '#A6A6A6' },
];

const RECENT_ACCESS = [
  { memberName: 'Jean Dupont',    club: 'Brussels', time: '11:45', result: 'Granted' },
  { memberName: 'Clara Morin',    club: 'Brussels', time: '11:07', result: 'Denied'  },
  { memberName: 'Pierre Dumont',  club: 'Brussels', time: '10:22', result: 'Denied'  },
  { memberName: 'Sophie Leroy',   club: 'Brussels', time: '10:05', result: 'Granted' },
  { memberName: 'Unknown',        club: 'Namur',    time: '09:01', result: 'Denied'  },
];

const UPCOMING_SESSIONS = [
  { course: 'Power Yoga', instructor: 'M. Laurent', club: 'Brussels', time: '14:00', capacity: 20, enrolled: 18 },
  { course: 'HIIT Cardio', instructor: 'R. Moreau', club: 'Liège',    time: '15:30', capacity: 15, enrolled: 15 },
  { course: 'Pilates',     instructor: 'S. Dupuis', club: 'Brussels', time: '17:00', capacity: 12, enrolled: 7  },
  { course: 'Boxing',      instructor: 'K. Osei',   club: 'Namur',    time: '18:30', capacity: 10, enrolled: 10 },
];

@Component({
  selector: 'app-dashboard',
  standalone: true,
  imports: [RouterLink, NgApexchartsModule, LucideAngularModule, DecimalPipe],
  template: `
<div class="flex flex-col h-full overflow-y-auto bg-[#F5F6FA]">
  <div class="p-8 flex flex-col gap-7">

    <!-- Header -->
    <div>
      <h1 class="text-2xl font-bold text-[#111827]">Dashboard</h1>
      <p class="text-sm text-[#6B7280] mt-0.5">Wednesday, 18 March 2026</p>
    </div>

    <!-- KPI Cards -->
    <div class="grid grid-cols-2 xl:grid-cols-4 gap-5">
      @for (kpi of kpiCards; track kpi.label) {
        <a [routerLink]="kpi.link" class="bg-white rounded-2xl p-5 shadow-sm border border-[#E0E0E0] hover:shadow-md transition-shadow block">
          <div class="flex items-start justify-between mb-4">
            <div [class]="'w-11 h-11 rounded-xl flex items-center justify-center shrink-0 ' + kpi.bg">
              <lucide-icon [img]="kpi.icon" [size]="20" [style.color]="kpi.accent"></lucide-icon>
            </div>
            <span [class]="'flex items-center gap-1 text-xs font-semibold ' + (kpi.trend >= 0 ? 'text-[#00B69B]' : 'text-[#FF4747]')">
              @if (kpi.trend >= 0) {
                <lucide-icon [img]="TrendUpIcon" [size]="14"></lucide-icon>
              } @else {
                <lucide-icon [img]="TrendDownIcon" [size]="14"></lucide-icon>
              }
              {{ absTrend(kpi.trend) | number:'1.1-1' }}%
            </span>
          </div>
          <p class="text-2xl font-black text-[#111827] leading-tight">{{ kpi.value }}</p>
          <p class="text-[13px] font-semibold text-[#6B7280] mt-0.5">{{ kpi.label }}</p>
          <p class="text-[11px] text-[#A6A6A6] mt-1">{{ kpi.sub }}</p>
        </a>
      }
    </div>

    <!-- Revenue Chart + Member Status -->
    <div class="grid grid-cols-1 xl:grid-cols-[1fr_320px] gap-5">
      <div class="bg-white rounded-2xl p-6 shadow-sm border border-[#E0E0E0]">
        <div class="flex items-center justify-between mb-5">
          <div>
            <h2 class="text-[17px] font-bold text-[#111827]">Monthly Revenue</h2>
            <p class="text-sm text-[#6B7280]">Last 12 months</p>
          </div>
        </div>
        <apx-chart
          [series]="revenueSeries"
          [chart]="revenueChart"
          [xaxis]="revenueXaxis"
          [yaxis]="revenueYaxis"
          [stroke]="revenueStroke"
          [fill]="revenueFill"
          [colors]="['#4880FF']"
          [dataLabels]="noDataLabels"
          [grid]="chartGrid"
          [tooltip]="revenueTooltip"
        ></apx-chart>
      </div>

      <!-- Member Status -->
      <div class="bg-white rounded-2xl p-6 shadow-sm border border-[#E0E0E0] flex flex-col">
        <h2 class="text-[17px] font-bold text-[#111827] mb-1">Member Status</h2>
        <p class="text-sm text-[#6B7280] mb-5">{{ totalMembers }} total members</p>

        <div class="flex items-center justify-center my-2">
          <div class="relative w-32 h-32">
            <svg class="w-full h-full -rotate-90" viewBox="0 0 120 120">
              <circle cx="60" cy="60" r="50" fill="none" stroke="#F0F0F0" stroke-width="14"/>
              <circle cx="60" cy="60" r="50" fill="none" stroke="#00B69B" stroke-width="14"
                [attr.stroke-dasharray]="activePct * 314 / 100 + ' 314'" stroke-linecap="round"/>
            </svg>
            <div class="absolute inset-0 flex flex-col items-center justify-center">
              <span class="text-xl font-black text-[#111827]">{{ activePct }}%</span>
              <span class="text-[10px] text-[#6B7280] font-medium">Active</span>
            </div>
          </div>
        </div>

        <div class="flex flex-col gap-3 mt-4">
          @for (s of memberStatus; track s.label) {
            <div class="flex items-center justify-between">
              <div class="flex items-center gap-2.5">
                <div class="w-2.5 h-2.5 rounded-full" [style.background-color]="s.color"></div>
                <span class="text-sm font-medium text-[#505050]">{{ s.label }}</span>
              </div>
              <div class="flex items-center gap-3">
                <div class="w-24 h-1.5 bg-[#F0F0F0] rounded-full overflow-hidden">
                  <div class="h-full rounded-full" [style.width.%]="s.value / totalMembers * 100" [style.background-color]="s.color"></div>
                </div>
                <span class="text-sm font-bold text-[#111827] w-8 text-right">{{ s.value }}</span>
              </div>
            </div>
          }
        </div>
        <a routerLink="/members" class="mt-5 text-center text-sm text-[#4880FF] font-semibold hover:underline">View all members →</a>
      </div>
    </div>

    <!-- Bottom row -->
    <div class="grid grid-cols-1 xl:grid-cols-3 gap-5">

      <!-- Recent Access -->
      <div class="bg-white rounded-2xl shadow-sm border border-[#E0E0E0] overflow-hidden">
        <div class="px-5 py-4 border-b border-[#F0F0F0] flex items-center justify-between">
          <h2 class="text-[15px] font-bold text-[#111827]">Recent Access</h2>
          <a routerLink="/access-control" class="text-xs text-[#4880FF] font-semibold hover:underline">View all</a>
        </div>
        <div class="divide-y divide-[#F5F5F5]">
          @for (a of recentAccess; track $index) {
            <div class="flex items-center justify-between px-5 py-3">
              <div class="flex items-center gap-3 min-w-0">
                @if (a.result === 'Granted') {
                  <lucide-icon [img]="CheckCircleIcon" [size]="16" class="text-[#00B69B] shrink-0"></lucide-icon>
                } @else {
                  <lucide-icon [img]="XCircleIcon" [size]="16" class="text-[#FF4747] shrink-0"></lucide-icon>
                }
                <div class="min-w-0">
                  <p class="text-sm font-semibold text-[#111827] truncate">{{ a.memberName }}</p>
                  <p class="text-xs text-[#A6A6A6]">{{ a.club }}</p>
                </div>
              </div>
              <div class="flex items-center gap-1.5 text-xs text-[#A6A6A6] shrink-0">
                <lucide-icon [img]="ClockIcon" [size]="12"></lucide-icon> {{ a.time }}
              </div>
            </div>
          }
        </div>
      </div>

      <!-- Today's Sessions -->
      <div class="bg-white rounded-2xl shadow-sm border border-[#E0E0E0] overflow-hidden">
        <div class="px-5 py-4 border-b border-[#F0F0F0] flex items-center justify-between">
          <h2 class="text-[15px] font-bold text-[#111827]">Today's Sessions</h2>
          <a routerLink="/courses/schedule" class="text-xs text-[#4880FF] font-semibold hover:underline">Schedule</a>
        </div>
        <div class="divide-y divide-[#F5F5F5]">
          @for (s of upcomingSessions; track $index) {
            <div class="px-5 py-3">
              <div class="flex items-start justify-between mb-1">
                <div>
                  <p class="text-sm font-semibold text-[#111827]">{{ s.course }}</p>
                  <p class="text-xs text-[#A6A6A6]">{{ s.instructor }} · {{ s.club }}</p>
                </div>
                <div class="flex items-center gap-1 text-xs text-[#6B7280] shrink-0 ml-3">
                  <lucide-icon [img]="ClockIcon" [size]="12"></lucide-icon> {{ s.time }}
                </div>
              </div>
              <div class="flex items-center gap-2 mt-1.5">
                <div class="flex-1 h-1.5 bg-[#F0F0F0] rounded-full overflow-hidden">
                  <div class="h-full rounded-full" [class]="s.enrolled >= s.capacity ? 'bg-[#FF4747]' : 'bg-[#4880FF]'"
                    [style.width.%]="s.enrolled / s.capacity * 100"></div>
                </div>
                <span class="text-[11px] font-bold" [class]="s.enrolled >= s.capacity ? 'text-[#FF4747]' : 'text-[#6B7280]'">
                  {{ s.enrolled }}/{{ s.capacity }}
                </span>
              </div>
            </div>
          }
        </div>
      </div>

      <!-- Equipment + Contracts Bar -->
      <div class="bg-white rounded-2xl shadow-sm border border-[#E0E0E0] overflow-hidden flex flex-col">
        <div class="px-5 py-4 border-b border-[#F0F0F0] flex items-center justify-between">
          <h2 class="text-[15px] font-bold text-[#111827]">Equipment</h2>
          <a routerLink="/equipment" class="text-xs text-[#4880FF] font-semibold hover:underline">View all</a>
        </div>
        <div class="flex flex-col gap-3 p-5">
          @for (eq of equipmentSummary; track eq.label) {
            <div class="flex items-center gap-3">
              <div [class]="'w-9 h-9 rounded-xl flex items-center justify-center shrink-0 ' + eq.bg">
                <lucide-icon [img]="eq.icon" [size]="16" [class]="eq.color"></lucide-icon>
              </div>
              <div class="flex-1"><p class="text-sm font-medium text-[#505050]">{{ eq.label }}</p></div>
              <span [class]="'text-lg font-black ' + eq.color">{{ eq.count }}</span>
            </div>
          }
        </div>
        <div class="px-5 pb-5 pt-2 border-t border-[#F5F5F5]">
          <p class="text-[13px] font-bold text-[#111827] mb-3">Contracts / Month</p>
          <apx-chart
            [series]="contractSeries"
            [chart]="contractChart"
            [xaxis]="contractXaxis"
            [yaxis]="contractYaxis"
            [colors]="['#4880FF']"
            [dataLabels]="noDataLabels"
            [plotOptions]="contractPlotOptions"
            [grid]="chartGrid"
          ></apx-chart>
        </div>
      </div>

    </div>
  </div>
</div>
  `,
})
export class DashboardComponent {
  readonly TrendUpIcon = TrendingUp;
  readonly TrendDownIcon = TrendingDown;
  readonly CheckCircleIcon = CheckCircle;
  readonly XCircleIcon = XCircle;
  readonly ClockIcon = Clock;

  totalMembers = MEMBER_STATUS_DATA.reduce((s, d) => s + d.value, 0);
  activePct = Math.round((782 / this.totalMembers) * 100);
  memberStatus = MEMBER_STATUS_DATA;
  recentAccess = RECENT_ACCESS;
  upcomingSessions = UPCOMING_SESSIONS;

  kpiCards = [
    { label: 'Active Members',   value: '782',      sub: 'out of 859 total',        trend: 5.2,  icon: Users,         accent: '#4880FF', bg: 'bg-[#EBEBFF]', link: '/members' },
    { label: 'Active Contracts', value: '651',      sub: '23 expiring soon',         trend: 2.1,  icon: FileText,      accent: '#00B69B', bg: 'bg-[#E0F8EA]', link: '/contracts' },
    { label: 'Revenue (March)',  value: '38 420 €', sub: 'from 651 invoices',        trend: 6.2,  icon: AlertTriangle, accent: '#8B5CF6', bg: 'bg-[#F3F0FF]', link: '/billing/invoices' },
    { label: 'Overdue Invoices', value: '18',       sub: '2 847 € outstanding',      trend: -3,   icon: AlertTriangle, accent: '#FF4747', bg: 'bg-[#FFF0F0]', link: '/billing/invoices' },
  ];

  equipmentSummary = [
    { label: 'In Service',  count: 142, color: 'text-[#00B69B]', bg: 'bg-[#E0F8EA]', icon: Dumbbell },
    { label: 'Maintenance', count: 8,   color: 'text-[#FF9066]', bg: 'bg-[#FFF3D6]', icon: Wrench   },
    { label: 'Broken',      count: 3,   color: 'text-[#FF4747]', bg: 'bg-[#FFF0F0]', icon: AlertTriangle },
  ];

  // Charts
  revenueSeries = [{ name: 'Revenue (€)', data: MONTHLY_REVENUE.map(m => m.revenue) }];
  revenueChart  = { type: 'area' as const, height: 240, toolbar: { show: false }, zoom: { enabled: false } };
  revenueXaxis  = { categories: MONTHLY_REVENUE.map(m => m.month), axisBorder: { show: false }, axisTicks: { show: false }, labels: { style: { colors: '#A6A6A6', fontSize: '11px' } } };
  revenueYaxis  = { labels: { formatter: (v: number) => `${(v / 1000).toFixed(0)}k`, style: { colors: '#A6A6A6', fontSize: '11px' } } };
  revenueStroke = { curve: 'smooth' as const, width: 3 };
  revenueFill   = { type: 'gradient', gradient: { shadeIntensity: 1, opacityFrom: 0.2, opacityTo: 0, stops: [0, 95] } };
  revenueTooltip = { y: { formatter: (v: number) => `${v.toLocaleString('fr-BE')} €` } };

  last6 = MONTHLY_REVENUE.slice(-6);
  contractSeries     = [{ name: 'Contracts', data: this.last6.map(m => m.contracts) }];
  contractChart      = { type: 'bar' as const, height: 100, toolbar: { show: false }, zoom: { enabled: false } };
  contractXaxis      = { categories: this.last6.map(m => m.month), axisBorder: { show: false }, axisTicks: { show: false }, labels: { style: { colors: '#A6A6A6', fontSize: '10px' } } };
  contractYaxis      = { labels: { style: { colors: '#A6A6A6', fontSize: '10px' } } };
  contractPlotOptions = { bar: { borderRadius: 4, columnWidth: '60%' } };

  noDataLabels = { enabled: false };
  chartGrid    = { borderColor: '#F0F0F0', strokeDashArray: 3, xaxis: { lines: { show: false } } };

  absTrend(value: number): number {
    return Math.abs(value);
  }
}


<div class="page">
  <div class="page-header">
    <div>
      <div class="eyebrow">Welcome back</div>
      <h1>Dashboard</h1>
      <p class="text-muted">Suivez l’activité clubs, les membres et les classes à venir.</p>
    </div>
    <div class="header-actions">
      <select [(ngModel)]="clubId" (change)="loadMetrics()" [disabled]="loading || clubsLoading || !clubs.length">
        <option [ngValue]="null">Select club</option>
        <option *ngFor="let club of clubs; trackBy: trackByClub" [ngValue]="club.id">{{ club.name }}</option>
      </select>
      <button class="pill ghost" (click)="refresh()" [disabled]="loading || clubsLoading">Refresh</button>
    </div>
  </div>

  @let hasPartialErrors = !errorMessage && partialErrors.length > 0;
  @let firstUpcomingSessions = firstSessions();
  @let upcomingSessionsCount = upcomingSessions.length;
  @let riskAlertsCount = riskAlerts.length;

  <div class="status info" *ngIf="clubsLoading">Refreshing clubs and metrics...</div>
  <div class="status warn" *ngIf="clubsErrorMessage">{{ clubsErrorMessage }}</div>
  <div class="status info" *ngIf="infoMessage">{{ infoMessage }}</div>
  <div class="status error" *ngIf="errorMessage">{{ errorMessage }}</div>
  <div class="status warn" *ngIf="hasPartialErrors">
    <div>Some widgets could not be refreshed:</div>
    <ul>
      <li *ngFor="let issue of partialErrors; trackBy: trackByError">{{ issue }}</li>
    </ul>
  </div>

  <div class="text-muted" *ngIf="lastUpdated">Last refresh: {{ lastUpdated | date:'short' }}</div>
  <div class="loading-state" *ngIf="loading">Loading dashboard data...</div>

  <ng-container *ngIf="!loading">
    <div class="stats grid-3">
      <div class="card stat">
        <div class="stat-label">Membres</div>
        <div class="stat-value">{{ stats.members }}</div>
        <div class="stat-sub text-muted">Total base active</div>
      </div>
      <div class="card stat">
        <div class="stat-label">Sessions prévues</div>
        <div class="stat-value">{{ stats.sessions }}</div>
        <div class="stat-sub text-muted">Sur les 14 prochains jours</div>
      </div>
      <div class="card stat">
        <div class="stat-label">Risques détectés</div>
        <div class="stat-value">{{ stats.risks }}</div>
        <div class="stat-sub text-muted">Scores de churn à surveiller</div>
      </div>
      <div class="card stat">
        <div class="stat-label">Clubs disponibles</div>
        <div class="stat-value">{{ stats.clubs }}</div>
        <div class="stat-sub text-muted">Référence active pour les vues planning</div>
      </div>
    </div>

    <div class="grid-2">
      <div class="card">
        <div class="flex-between">
          <div>
            <h3>Sessions à venir</h3>
            <p class="text-muted">Priorisez les créneaux qui se remplissent vite.</p>
          </div>
          <span class="pill muted">{{ upcomingSessionsCount }} sessions</span>
        </div>

        <div class="session-list" *ngIf="firstUpcomingSessions.length; else noSessions">
          <div class="session" *ngFor="let session of firstUpcomingSessions; trackBy: trackBySession">
            <div>
              <div class="session-name">{{ session.courseName }}</div>
              <div class="text-muted">{{ session.instructorName }} · {{ session.clubName }}</div>
            </div>
            <div class="pill muted">{{ session.startsAt | date:'medium' }}</div>
          </div>
        </div>
        <ng-template #noSessions>
          <div class="empty">Aucune session disponible pour l’instant.</div>
        </ng-template>
      </div>

      <div class="card">
        <div class="flex-between">
          <div>
            <h3>Alertes risque</h3>
            <p class="text-muted">Members à contacter en priorité.</p>
          </div>
          <span class="pill muted">{{ riskAlertsCount }} alertes</span>
        </div>

        <div class="risk-list" *ngIf="riskAlerts.length; else noRisk">
          <div class="risk" *ngFor="let alert of riskAlerts; trackBy: trackByRisk">
            <div>
              <div class="risk-name">{{ alert.memberName || 'Member' }}</div>
              <div class="text-muted">Score: {{ alert.score }}</div>
            </div>
            <span class="pill warn">High</span>
          </div>
        </div>
        <ng-template #noRisk>
          <div class="empty">Pas d’alertes ouvertes.</div>
        </ng-template>
      </div>
    </div>

    <div class="card quick-actions">
      <div class="flex-between">
        <h3>Actions rapides</h3>
        <span class="text-muted">Pour gagner du temps côté réception</span>
      </div>
      <div class="actions">
        <button *ngFor="let action of quickActions; trackBy: trackByAction" class="action-btn" (click)="runQuickAction(action)">
          <span class="icon">{{ action.icon }}</span>
          {{ action.label }}
        </button>
      </div>
      <p class="text-muted helper-text">Chaque action précise la page à ouvrir pour terminer l’opération.</p>
    </div>
  </ng-container>
  <div class="card" *ngIf="showEmptyState">
    <div class="empty">No activity data is available yet for this dashboard.</div>
  </div>
  <div class="card" *ngIf="!loading && !clubs.length">
    <div class="empty">
      Aucun club disponible. Vérifiez les droits d'accès (401/403) ou l'état de l'API.
      <div style="margin-top: 0.5rem;">
        <button class="pill ghost" (click)="loadClubsAndMetrics()" [disabled]="loading || clubsLoading">Retry</button>
      </div>
    </div>
  </div>
  <div class="card quick-actions" *ngIf="loading">
    <div class="flex-between">
      <h3>Actions rapides</h3>
      <span class="text-muted">Chargement des données...</span>
    </div>
    <div class="actions">
      <button *ngFor="let action of quickActions; trackBy: trackByAction" class="action-btn" disabled>
        <span class="icon">{{ action.icon }}</span>
        {{ action.label }}
      </button>
    </div>
  </div>
</div>
