// frontend/src/app/pages/guests/guests.component.ts
import { Component, OnInit, computed, inject, signal } from '@angular/core';
import { HttpErrorResponse } from '@angular/common/http';
import { FormsModule } from '@angular/forms';
import { LucideAngularModule, UserPlus, Plus, X, Check, Search, ShieldAlert } from 'lucide-angular';
import { GuestResponse, GuestsApiService } from '../../shared/services/guests-api.service';

type GuestStatus = 'Active' | 'Banned' | string;

interface Guest {
  id: number;
  firstName: string;
  lastName: string;
  dateOfBirth: string;
  email: string | null;
  status: GuestStatus;
  sponsorName: string;
  sponsorMemberId: number;
}

interface GuestForm {
  firstName: string;
  lastName: string;
  dateOfBirth: string;
  email: string;
  sponsorMemberId: string;
}

const PAGE_SIZE = 50;
const STATUS_CLASSES: Record<'active' | 'banned', string> = {
  active: 'bg-[#E0F8EA] text-[#00B69B]',
  banned: 'bg-[#FFF0F0] text-[#FF4747]',
};

const emptyForm = (): GuestForm => ({
  firstName: '',
  lastName: '',
  dateOfBirth: '',
  email: '',
  sponsorMemberId: '',
});

@Component({
  selector: 'app-guests',
  standalone: true,
  imports: [FormsModule, LucideAngularModule],
  template: `
<div class="flex flex-col h-full overflow-hidden bg-[#F5F6FA]">
  <div class="bg-white border-b border-[#E0E0E0] px-8 py-5 flex-shrink-0">
    <div class="flex items-center justify-between flex-wrap gap-4">
      <div>
        <h1 class="text-2xl font-bold text-[#111827] flex items-center gap-2">
          <lucide-icon [img]="UserPlusIcon" [size]="24" class="text-[#4880FF]"></lucide-icon>
          Guests
        </h1>
        <p class="text-sm text-[#6B7280] mt-1">
          {{ loading() ? 'Loading guests…' : (totalCount() + ' guest' + (totalCount() !== 1 ? 's' : '')) }}
        </p>
      </div>
      <div class="flex items-center gap-3 flex-wrap">
        <div class="flex items-center gap-2 bg-[#F5F6FA] border border-[#E0E0E0] rounded-xl px-3 py-2 w-56">
          <lucide-icon [img]="SearchIcon" [size]="16" class="text-[#A6A6A6] shrink-0"></lucide-icon>
          <input
            type="text"
            [ngModel]="search()"
            (ngModelChange)="search.set($event)"
            placeholder="Search…"
            class="text-sm bg-transparent focus:outline-none w-full placeholder:text-[#A6A6A6]" />
        </div>
        <button
          (click)="openCreateModal()"
          class="flex items-center gap-2 px-4 py-2 bg-[#4880FF] rounded-xl text-sm font-bold text-white shadow-[0_4px_15px_rgba(72,128,255,0.25)] hover:bg-[#3b6ee0] transition-all disabled:opacity-60"
          [disabled]="saving()">
          <lucide-icon [img]="PlusIcon" [size]="16"></lucide-icon>
          Register guest
        </button>
      </div>
    </div>
  </div>

  <div class="flex-1 overflow-y-auto p-8 space-y-4">
    @if (error()) {
      <div class="rounded-xl border border-[#FFD2D2] bg-[#FFF5F5] px-4 py-3 text-sm text-[#C53030]">
        {{ error() }}
      </div>
    }

    <div class="bg-white rounded-2xl shadow-sm border border-[#E0E0E0] overflow-hidden">
      @if (loading()) {
        <div class="px-5 py-12 text-center text-sm text-[#A6A6A6]">Loading guests...</div>
      } @else {
        <table class="w-full">
          <thead>
            <tr class="border-b border-[#E0E0E0] bg-[#F8FAFF]">
              @for (h of headers; track h) {
                <th class="text-left text-xs font-bold text-[#6B7280] uppercase px-5 py-3">{{ h }}</th>
              }
            </tr>
          </thead>
          <tbody>
            @if (filteredGuests().length === 0) {
              <tr>
                <td colspan="6" class="px-5 py-12 text-center text-sm text-[#A6A6A6]">No guests found</td>
              </tr>
            }
            @for (guest of filteredGuests(); track guest.id) {
              <tr class="border-b border-[#F0F0F0] hover:bg-[#F8FAFF] transition-colors">
                <td class="px-5 py-4">
                  <div class="flex items-center gap-3">
                    <div class="w-8 h-8 rounded-full bg-[#EBEBFF] text-[#4880FF] flex items-center justify-center text-sm font-bold shrink-0">
                      {{ guest.firstName[0] }}{{ guest.lastName[0] }}
                    </div>
                    <span class="font-bold text-[#111827]">{{ guest.firstName }} {{ guest.lastName }}</span>
                  </div>
                </td>
                <td class="px-5 py-4 text-sm text-[#6B7280]">{{ guest.dateOfBirth || '—' }}</td>
                <td class="px-5 py-4 text-sm text-[#6B7280]">{{ displayEmail(guest) }}</td>
                <td class="px-5 py-4 text-sm font-semibold text-[#4880FF]">{{ guest.sponsorName }}</td>
                <td class="px-5 py-4">
                  <span [class]="'text-xs font-bold px-2.5 py-1 rounded-full ' + statusClass(guest.status)">
                    {{ guest.status }}
                  </span>
                </td>
                <td class="px-5 py-4">
                  @if (!isBanned(guest.status)) {
                    <button
                      (click)="openBanConfirm(guest)"
                      class="flex items-center gap-1 text-sm text-[#FF4747] font-semibold hover:underline disabled:opacity-60"
                      [disabled]="banning()">
                      <lucide-icon [img]="ShieldAlertIcon" [size]="14"></lucide-icon>
                      Ban
                    </button>
                  }
                </td>
              </tr>
            }
          </tbody>
        </table>
      }
    </div>

    @if (!loading() && totalCount() > 0) {
      <div class="flex items-center justify-between">
        <p class="text-sm text-[#6B7280]">
          {{ startItem() }}-{{ endItem() }} of {{ totalCount() }} guests
        </p>
        <div class="flex items-center gap-2">
          <button
            (click)="goToPreviousPage()"
            class="px-3 py-1.5 text-sm border border-[#E0E0E0] rounded-lg bg-white hover:bg-[#F8FAFF] disabled:opacity-50"
            [disabled]="page() <= 1 || loading()">
            Previous
          </button>
          <span class="text-sm text-[#6B7280]">Page {{ page() }} / {{ totalPages() }}</span>
          <button
            (click)="goToNextPage()"
            class="px-3 py-1.5 text-sm border border-[#E0E0E0] rounded-lg bg-white hover:bg-[#F8FAFF] disabled:opacity-50"
            [disabled]="page() >= totalPages() || loading()">
            Next
          </button>
        </div>
      </div>
    }
  </div>

  @if (showModal()) {
    <div class="fixed inset-0 bg-black/40 backdrop-blur-sm z-50 flex items-center justify-center p-4" (click)="closeCreateModal()">
      <div class="bg-white rounded-2xl p-6 w-full max-w-lg shadow-xl" (click)="$event.stopPropagation()">
        <div class="flex items-center justify-between mb-6">
          <h3 class="text-xl font-bold text-[#111827]">Register a guest</h3>
          <button (click)="closeCreateModal()" class="p-1.5 rounded-lg text-[#6B7280] hover:bg-[#F5F6FA]">
            <lucide-icon [img]="XIcon" [size]="20"></lucide-icon>
          </button>
        </div>

        @if (modalError()) {
          <div class="rounded-xl border border-[#FFD2D2] bg-[#FFF5F5] px-4 py-3 mb-4 text-sm text-[#C53030]">
            {{ modalError() }}
          </div>
        }

        <div class="space-y-4">
          <div>
            <label class="block text-sm font-medium text-[#6B7280] mb-1">Sponsor member ID</label>
            <input
              class="input-field"
              type="number"
              [ngModel]="form().sponsorMemberId"
              (ngModelChange)="patchForm('sponsorMemberId', $event?.toString() ?? '')"
              placeholder="123" />
            <p class="text-xs text-[#A6A6A6] mt-1">Enter an existing member id.</p>
          </div>

          <div class="grid grid-cols-2 gap-4">
            <div>
              <label class="block text-sm font-medium text-[#6B7280] mb-1">First name</label>
              <input
                class="input-field"
                [ngModel]="form().firstName"
                (ngModelChange)="patchForm('firstName', $event?.toString() ?? '')"
                placeholder="Alice" />
            </div>
            <div>
              <label class="block text-sm font-medium text-[#6B7280] mb-1">Last name</label>
              <input
                class="input-field"
                [ngModel]="form().lastName"
                (ngModelChange)="patchForm('lastName', $event?.toString() ?? '')"
                placeholder="Fontaine" />
            </div>
          </div>

          <div class="grid grid-cols-2 gap-4">
            <div>
              <label class="block text-sm font-medium text-[#6B7280] mb-1">Date of birth</label>
              <input
                class="input-field"
                type="date"
                [ngModel]="form().dateOfBirth"
                (ngModelChange)="patchForm('dateOfBirth', $event?.toString() ?? '')" />
            </div>
            <div>
              <label class="block text-sm font-medium text-[#6B7280] mb-1">Email</label>
              <input
                class="input-field"
                type="email"
                [ngModel]="form().email"
                (ngModelChange)="patchForm('email', $event?.toString() ?? '')"
                placeholder="alice@email.com" />
            </div>
          </div>
        </div>

        <div class="flex gap-3 mt-8">
          <button
            (click)="closeCreateModal()"
            class="flex-1 py-2.5 bg-[#F5F6FA] text-[#6B7280] font-semibold rounded-xl hover:bg-[#E0E0E0] transition-colors disabled:opacity-60"
            [disabled]="saving()">
            Cancel
          </button>
          <button
            (click)="handleCreate()"
            class="flex-1 py-2.5 bg-[#4880FF] text-white font-semibold rounded-xl hover:bg-[#3b6ee0] transition-colors flex items-center justify-center gap-2 disabled:opacity-60"
            [disabled]="saving()">
            <lucide-icon [img]="CheckIcon" [size]="16"></lucide-icon>
            {{ saving() ? 'Registering...' : 'Register guest' }}
          </button>
        </div>
      </div>
    </div>
  }

  @if (showBanConfirm()) {
    <div class="fixed inset-0 bg-black/40 backdrop-blur-sm z-50 flex items-center justify-center p-4" (click)="closeBanConfirm()">
      <div class="bg-white rounded-2xl p-6 w-full max-w-sm shadow-xl" (click)="$event.stopPropagation()">
        <div class="flex items-center gap-3 mb-4">
          <div class="w-10 h-10 rounded-xl bg-[#FFF0F0] flex items-center justify-center">
            <lucide-icon [img]="ShieldAlertIcon" [size]="20" class="text-[#FF4747]"></lucide-icon>
          </div>
          <h3 class="text-lg font-bold text-[#111827]">Ban this guest?</h3>
        </div>
        <p class="text-sm text-[#6B7280] mb-6">
          <span class="font-bold text-[#111827]">{{ showBanConfirm()!.firstName }} {{ showBanConfirm()!.lastName }}</span>
          will be denied access to all clubs.
        </p>

        @if (banError()) {
          <div class="rounded-xl border border-[#FFD2D2] bg-[#FFF5F5] px-4 py-3 mb-4 text-sm text-[#C53030]">
            {{ banError() }}
          </div>
        }

        <div class="flex gap-3">
          <button
            (click)="closeBanConfirm()"
            class="flex-1 py-2.5 bg-[#F5F6FA] text-[#6B7280] font-semibold rounded-xl hover:bg-[#E0E0E0] transition-colors disabled:opacity-60"
            [disabled]="banning()">
            Cancel
          </button>
          <button
            (click)="handleBanConfirmed()"
            class="flex-1 py-2.5 bg-[#FF4747] text-white font-semibold rounded-xl hover:bg-[#e03d3d] transition-colors disabled:opacity-60"
            [disabled]="banning()">
            {{ banning() ? 'Banning...' : 'Confirm ban' }}
          </button>
        </div>
      </div>
    </div>
  }
</div>
  `,
  styles: [`
    .input-field {
      @apply w-full bg-[#F5F6FA] border border-[#E0E0E0] rounded-xl px-4 py-2.5 text-[#111827] text-sm focus:outline-none focus:border-[#4880FF] focus:ring-1 focus:ring-[#4880FF];
    }
  `],
})
export class GuestsComponent implements OnInit {
  readonly UserPlusIcon = UserPlus;
  readonly PlusIcon = Plus;
  readonly XIcon = X;
  readonly CheckIcon = Check;
  readonly SearchIcon = Search;
  readonly ShieldAlertIcon = ShieldAlert;

  readonly headers = ['Name', 'Date of birth', 'Email', 'Sponsor', 'Status', ''];

  private readonly guestsApi = inject(GuestsApiService);

  readonly guests = signal<Guest[]>([]);
  readonly loading = signal(true);
  readonly error = signal<string | null>(null);

  readonly search = signal('');
  readonly page = signal(1);
  readonly totalCount = signal(0);
  readonly totalPages = computed(() => Math.max(1, Math.ceil(this.totalCount() / PAGE_SIZE)));
  readonly startItem = computed(() => (this.totalCount() === 0 ? 0 : (this.page() - 1) * PAGE_SIZE + 1));
  readonly endItem = computed(() => {
    if (this.totalCount() === 0) return 0;
    return Math.min((this.page() - 1) * PAGE_SIZE + this.guests().length, this.totalCount());
  });

  readonly showModal = signal(false);
  readonly showBanConfirm = signal<Guest | null>(null);
  readonly form = signal<GuestForm>(emptyForm());
  readonly saving = signal(false);
  readonly banning = signal(false);
  readonly modalError = signal<string | null>(null);
  readonly banError = signal<string | null>(null);

  readonly filteredGuests = computed(() => {
    const query = this.search().trim().toLowerCase();
    if (!query) return this.guests();

    return this.guests().filter((guest) => {
      const fullName = `${guest.firstName} ${guest.lastName}`.toLowerCase();
      const email = guest.email?.toLowerCase() ?? '';
      return fullName.includes(query)
        || email.includes(query)
        || guest.sponsorName.toLowerCase().includes(query)
        || String(guest.sponsorMemberId).includes(query);
    });
  });

  ngOnInit(): void {
    this.loadGuests();
  }

  statusClass(status: GuestStatus): string {
    if (this.isBanned(status)) return STATUS_CLASSES.banned;
    if (status.toLowerCase() === 'active') return STATUS_CLASSES.active;
    return 'bg-[#F5F6FA] text-[#6B7280]';
  }

  isBanned(status: GuestStatus): boolean {
    return status.toLowerCase() === 'banned';
  }

  displayEmail(guest: Guest): string {
    return guest.email?.trim() || '—';
  }

  patchForm<K extends keyof GuestForm>(key: K, value: string): void {
    this.form.update((current) => ({ ...current, [key]: value }));
  }

  openCreateModal(): void {
    this.form.set(emptyForm());
    this.modalError.set(null);
    this.showModal.set(true);
  }

  closeCreateModal(): void {
    if (this.saving()) return;
    this.showModal.set(false);
    this.modalError.set(null);
  }

  openBanConfirm(guest: Guest): void {
    this.showBanConfirm.set(guest);
    this.banError.set(null);
  }

  closeBanConfirm(): void {
    if (this.banning()) return;
    this.showBanConfirm.set(null);
    this.banError.set(null);
  }

  goToPreviousPage(): void {
    if (this.page() <= 1 || this.loading()) return;
    this.page.update((current) => current - 1);
    this.loadGuests();
  }

  goToNextPage(): void {
    if (this.page() >= this.totalPages() || this.loading()) return;
    this.page.update((current) => current + 1);
    this.loadGuests();
  }

  handleCreate(): void {
    const payload = this.form();
    const sponsorMemberId = this.parsePositiveInteger(payload.sponsorMemberId);

    if (!payload.firstName.trim() || !payload.lastName.trim() || !payload.dateOfBirth || !payload.email.trim()) {
      this.modalError.set('Please fill all required fields.');
      return;
    }

    if (sponsorMemberId === null) {
      this.modalError.set('Sponsor member ID must be a valid positive number.');
      return;
    }

    this.saving.set(true);
    this.modalError.set(null);

    this.guestsApi.createGuest({
      sponsorMemberId,
      firstName: payload.firstName.trim(),
      lastName: payload.lastName.trim(),
      dateOfBirth: payload.dateOfBirth,
      email: payload.email.trim(),
    }).subscribe({
      next: () => {
        this.saving.set(false);
        this.showModal.set(false);
        this.form.set(emptyForm());
        this.page.set(1);
        this.loadGuests();
      },
      error: (error: unknown) => {
        this.saving.set(false);
        this.modalError.set(this.resolveErrorMessage(error, 'Unable to register guest.'));
      },
    });
  }

  handleBanConfirmed(): void {
    const guest = this.showBanConfirm();
    if (!guest || this.banning()) return;

    this.banning.set(true);
    this.banError.set(null);

    this.guestsApi.banGuest(guest.id).subscribe({
      next: () => {
        this.banning.set(false);
        this.showBanConfirm.set(null);
        this.loadGuests();
      },
      error: (error: unknown) => {
        this.banning.set(false);
        this.banError.set(this.resolveErrorMessage(error, 'Unable to ban guest.'));
      },
    });
  }

  private loadGuests(): void {
    this.loading.set(true);
    this.error.set(null);

    this.guestsApi.listGuests(this.page(), PAGE_SIZE).subscribe({
      next: (response) => {
        const totalCount = typeof response.totalCount === 'number' ? response.totalCount : response.items.length;
        this.guests.set((response.items ?? []).map((guest) => this.mapGuest(guest)));
        this.totalCount.set(totalCount);

        if (response.totalPages > 0 && this.page() > response.totalPages) {
          this.page.set(response.totalPages);
          this.loadGuests();
          return;
        }

        this.loading.set(false);
      },
      error: (error: unknown) => {
        this.loading.set(false);
        this.error.set(this.resolveErrorMessage(error, 'Unable to load guests.'));
      },
    });
  }

  private mapGuest(guest: GuestResponse): Guest {
    return {
      id: guest.id,
      firstName: guest.firstName,
      lastName: guest.lastName,
      dateOfBirth: guest.dateOfBirth,
      email: guest.email ?? null,
      status: this.normalizeStatus(guest.status),
      sponsorMemberId: guest.sponsorMemberId,
      sponsorName: guest.sponsorName || '—',
    };
  }

  private normalizeStatus(status: string | null | undefined): GuestStatus {
    const normalized = (status ?? '').trim().toLowerCase();
    if (normalized === 'active') return 'Active';
    if (normalized === 'banned') return 'Banned';
    return status?.trim() || 'Unknown';
  }

  private parsePositiveInteger(value: string): number | null {
    const parsed = Number(value);
    return Number.isInteger(parsed) && parsed > 0 ? parsed : null;
  }

  private resolveErrorMessage(error: unknown, fallback: string): string {
    if (!(error instanceof HttpErrorResponse)) return fallback;
    return this.extractApiMessage(error.error) ?? fallback;
  }

  private extractApiMessage(payload: unknown): string | null {
    if (typeof payload === 'string' && payload.trim()) {
      return payload.trim();
    }

    if (typeof payload !== 'object' || payload === null) {
      return null;
    }

    const record = payload as Record<string, unknown>;
    const directMessage = record['message'];
    if (typeof directMessage === 'string' && directMessage.trim()) {
      return directMessage.trim();
    }

    const title = record['title'];
    if (typeof title === 'string' && title.trim()) {
      return title.trim();
    }

    const errors = record['errors'];
    if (Array.isArray(errors)) {
      const firstError = errors.find((item): item is string => typeof item === 'string' && item.trim().length > 0);
      return firstError?.trim() ?? null;
    }

    if (typeof errors === 'object' && errors !== null) {
      for (const value of Object.values(errors)) {
        if (!Array.isArray(value)) continue;
        const firstEntry = value.find((item): item is string => typeof item === 'string' && item.trim().length > 0);
        if (firstEntry) return firstEntry.trim();
      }
    }

    return null;
  }
}

<div class="guests-container">
  <div class="page-header">
    <div>
      <h2>Guests</h2>
      <p class="text-muted">Invités et passages accompagnés.</p>
    </div>
  </div>

  <div class="form-card">
    <h3>Register guest</h3>
    <div class="error" *ngIf="formError">{{ formError }}</div>
    <div class="form-grid">
      <label>Sponsor member lookup
        <input type="search" [ngModel]="sponsorLookupTerm" (ngModelChange)="onSponsorLookupChange($event)" placeholder="Name or email">
      </label>
      <label>Sponsor member ID
        <input type="number" [(ngModel)]="form.sponsorMemberId">
      </label>
      <label>First name
        <input type="text" [(ngModel)]="form.firstName">
      </label>
      <label>Last name
        <input type="text" [(ngModel)]="form.lastName">
      </label>
      <label>Email
        <input type="email" [(ngModel)]="form.email">
      </label>
      <label>Date of birth
        <input type="date" [(ngModel)]="form.dateOfBirth">
      </label>
    </div>
    <div class="loading" *ngIf="sponsorLookupLoading">Searching members...</div>
    <div class="error" *ngIf="sponsorLookupError">{{ sponsorLookupError }}</div>
    <div class="lookup-results" *ngIf="sponsorLookupResults.length">
      <button
        type="button"
        class="lookup-item"
        *ngFor="let member of sponsorLookupResults"
        (click)="selectSponsor(member)"
      >
        <span>{{ member.firstName }} {{ member.lastName }}</span>
        <span>#{{ member.id }}</span>
      </button>
    </div>
    <button class="btn btn-primary" (click)="registerGuest()" [disabled]="submitting">
      {{ submitting ? 'Registering...' : 'Register' }}
    </button>
  </div>

  <div class="error" *ngIf="errorMessage">{{ errorMessage }}</div>
  <div class="success" *ngIf="successMessage">{{ successMessage }}</div>
  @let hasGuests = guests.length > 0;

  <div class="table-section">
    <div class="loading" *ngIf="loading">Loading guests...</div>
    <table *ngIf="!loading && hasGuests">
      <thead>
        <tr>
          <th>Name</th>
          <th>Sponsor</th>
          <th>Date of birth</th>
          <th>Status</th>
          <th>Actions</th>
        </tr>
      </thead>
      <tbody>
        <tr *ngFor="let guest of guests; trackBy: trackByGuest">
          @let canBan = canBanGuest(guest);
          @let isBanningCurrent = banningGuestId === guest.id;
          <td>{{ guest.firstName }} {{ guest.lastName }}</td>
          <td>{{ guest.sponsorName || guest.sponsorMemberId || '—' }}</td>
          <td>{{ guest.dateOfBirth | date:'mediumDate' }}</td>
          <td>{{ guest.status }}</td>
          <td>
            <ng-container *ngIf="pendingBanId !== guest.id; else confirmBan">
              <button class="btn btn-secondary" (click)="requestBanGuest(guest.id)" [disabled]="banningGuestId !== null || !canBan">
                {{ canBan ? 'Ban' : 'Banned' }}
              </button>
            </ng-container>
            <ng-template #confirmBan>
              <button class="btn btn-secondary" (click)="banGuest(guest.id)" [disabled]="isBanningCurrent">
                {{ isBanningCurrent ? 'Banning...' : 'Confirm' }}
              </button>
              <button class="btn btn-light" (click)="cancelBanGuest()" [disabled]="isBanningCurrent">Cancel</button>
            </ng-template>
          </td>
        </tr>
      </tbody>
    </table>
    <div class="empty-state" *ngIf="!loading && hasLoadedGuests && !hasGuests">No guests registered.</div>
  </div>
</div>

// dashstack(1)/src/app/pages/Guests.tsx
import { useState } from "react";
import { motion, AnimatePresence } from "motion/react";
import { UserPlus, Plus, X, Check, Search, ShieldAlert } from "lucide-react";
import { toast } from "sonner";

type GuestStatus = "Active" | "Banned";

interface Guest {
  id: number;
  firstName: string;
  lastName: string;
  dateOfBirth: string;
  email: string;
  status: GuestStatus;
  sponsorName: string;
  sponsorMemberId: number;
}

const MOCK_GUESTS: Guest[] = [
  { id: 1, firstName: "Alice", lastName: "Fontaine", dateOfBirth: "1995-07-22", email: "alice@email.com", status: "Active", sponsorName: "Jean Dupont", sponsorMemberId: 1 },
  { id: 2, firstName: "Bruno", lastName: "Renard", dateOfBirth: "1988-11-04", email: "bruno@email.com", status: "Active", sponsorName: "Marie Martin", sponsorMemberId: 2 },
  { id: 3, firstName: "Clara", lastName: "Morin", dateOfBirth: "2000-03-15", email: "clara@email.com", status: "Banned", sponsorName: "Jean Dupont", sponsorMemberId: 1 },
];

const MOCK_MEMBERS = [
  { id: 1, name: "Jean Dupont" },
  { id: 2, name: "Marie Martin" },
  { id: 3, name: "Luc Bernard" },
  { id: 4, name: "Sophie Leroy" },
];

const STATUS_CLASSES: Record<GuestStatus, string> = {
  Active: "bg-[#E0F8EA] text-[#00B69B]",
  Banned: "bg-[#FFF0F0] text-[#FF4747]",
};

const EMPTY_FORM = {
  firstName: "",
  lastName: "",
  dateOfBirth: "",
  email: "",
  sponsorMemberId: 1,
};

export function Guests() {
  const [guests, setGuests] = useState(MOCK_GUESTS);
  const [search, setSearch] = useState("");
  const [showModal, setShowModal] = useState(false);
  const [showBanConfirm, setShowBanConfirm] = useState<Guest | null>(null);
  const [form, setForm] = useState(EMPTY_FORM);
  const [sponsorSearch, setSponsorSearch] = useState("");

  const filtered = guests.filter(
    (g) =>
      `${g.firstName} ${g.lastName}`.toLowerCase().includes(search.toLowerCase()) ||
      g.email.toLowerCase().includes(search.toLowerCase()) ||
      g.sponsorName.toLowerCase().includes(search.toLowerCase())
  );

  const filteredMembers = MOCK_MEMBERS.filter((m) =>
    m.name.toLowerCase().includes(sponsorSearch.toLowerCase())
  );

  const handleCreate = () => {
    if (!form.firstName || !form.lastName || !form.email) {
      toast.error("First name, last name and email are required");
      return;
    }
    const sponsor = MOCK_MEMBERS.find((m) => m.id === Number(form.sponsorMemberId));
    const newGuest: Guest = {
      id: guests.length + 1,
      firstName: form.firstName,
      lastName: form.lastName,
      dateOfBirth: form.dateOfBirth,
      email: form.email,
      status: "Active",
      sponsorName: sponsor?.name ?? "—",
      sponsorMemberId: Number(form.sponsorMemberId),
    };
    setGuests([newGuest, ...guests]);
    toast.success(`Guest ${form.firstName} ${form.lastName} registered`);
    setShowModal(false);
    setForm(EMPTY_FORM);
    setSponsorSearch("");
  };

  const handleBan = (guest: Guest) => {
    setGuests(
      guests.map((g) =>
        g.id === guest.id ? { ...g, status: "Banned" } : g
      )
    );
    toast.success(`${guest.firstName} ${guest.lastName} has been banned`);
    setShowBanConfirm(null);
  };

  const inputClass =
    "w-full bg-[#F5F6FA] border border-[#E0E0E0] rounded-xl px-4 py-2.5 text-[#111827] focus:outline-none focus:border-[#4880FF] focus:ring-1 focus:ring-[#4880FF] text-sm";

  return (
    <div className="flex flex-col h-full overflow-hidden bg-[#F5F6FA]">
      {/* Header */}
      <div className="bg-white border-b border-[#E0E0E0] px-8 py-5 flex-shrink-0">
        <div className="flex items-center justify-between flex-wrap gap-4">
          <div>
            <h1 className="text-2xl font-bold text-[#111827] flex items-center gap-2">
              <UserPlus className="w-6 h-6 text-[#4880FF]" /> Guests
            </h1>
            <p className="text-sm text-[#6B7280] mt-1">
              {filtered.length} guest{filtered.length !== 1 ? "s" : ""}
            </p>
          </div>
          <div className="flex items-center gap-3">
            <div className="flex items-center gap-2 bg-[#F5F6FA] border border-[#E0E0E0] rounded-xl px-3 py-2 w-56">
              <Search className="w-4 h-4 text-[#A6A6A6] shrink-0" />
              <input
                type="text"
                placeholder="Search…"
                value={search}
                onChange={(e) => setSearch(e.target.value)}
                className="text-sm bg-transparent focus:outline-none w-full placeholder:text-[#A6A6A6]"
              />
            </div>
            <button
              onClick={() => { setShowModal(true); setForm(EMPTY_FORM); setSponsorSearch(""); }}
              className="flex items-center gap-2 px-4 py-2 bg-[#4880FF] rounded-xl text-sm font-bold text-white shadow-[0_4px_15px_rgba(72,128,255,0.25)] hover:bg-[#3b6ee0] transition-all"
            >
              <Plus className="w-4 h-4" /> Register guest
            </button>
          </div>
        </div>
      </div>

      {/* Table */}
      <div className="flex-1 overflow-y-auto p-8">
        <motion.div
          initial={{ opacity: 0, y: 20 }}
          animate={{ opacity: 1, y: 0 }}
          className="bg-white rounded-2xl shadow-sm border border-[#E0E0E0] overflow-hidden"
        >
          <table className="w-full">
            <thead>
              <tr className="border-b border-[#E0E0E0] bg-[#F8FAFF]">
                {["Name", "Date of birth", "Email", "Sponsor", "Status", ""].map((h) => (
                  <th key={h} className="text-left text-xs font-bold text-[#6B7280] uppercase px-5 py-3">{h}</th>
                ))}
              </tr>
            </thead>
            <tbody>
              {filtered.length === 0 ? (
                <tr>
                  <td colSpan={6} className="px-5 py-12 text-center text-sm text-[#A6A6A6]">No guests found</td>
                </tr>
              ) : (
                filtered.map((guest) => (
                  <tr key={guest.id} className="border-b border-[#F0F0F0] hover:bg-[#F8FAFF] transition-colors">
                    <td className="px-5 py-4">
                      <div className="flex items-center gap-3">
                        <div className="w-8 h-8 rounded-full bg-[#EBEBFF] text-[#4880FF] flex items-center justify-center text-sm font-bold shrink-0">
                          {guest.firstName[0]}{guest.lastName[0]}
                        </div>
                        <span className="font-bold text-[#111827]">
                          {guest.firstName} {guest.lastName}
                        </span>
                      </div>
                    </td>
                    <td className="px-5 py-4 text-sm text-[#6B7280]">{guest.dateOfBirth || "—"}</td>
                    <td className="px-5 py-4 text-sm text-[#6B7280]">{guest.email}</td>
                    <td className="px-5 py-4 text-sm font-semibold text-[#4880FF]">{guest.sponsorName}</td>
                    <td className="px-5 py-4">
                      <span className={`text-xs font-bold px-2.5 py-1 rounded-full ${STATUS_CLASSES[guest.status]}`}>
                        {guest.status}
                      </span>
                    </td>
                    <td className="px-5 py-4">
                      {guest.status !== "Banned" && (
                        <button
                          onClick={() => setShowBanConfirm(guest)}
                          className="flex items-center gap-1 text-sm text-[#FF4747] font-semibold hover:underline"
                        >
                          <ShieldAlert className="w-3.5 h-3.5" /> Ban
                        </button>
                      )}
                    </td>
                  </tr>
                ))
              )}
            </tbody>
          </table>
        </motion.div>
      </div>

      {/* Create Modal */}
      <AnimatePresence>
        {showModal && (
          <motion.div
            initial={{ opacity: 0 }}
            animate={{ opacity: 1 }}
            exit={{ opacity: 0 }}
            className="fixed inset-0 bg-black/40 backdrop-blur-sm z-50 flex items-center justify-center p-4"
            onClick={() => setShowModal(false)}
          >
            <motion.div
              initial={{ opacity: 0, scale: 0.95 }}
              animate={{ opacity: 1, scale: 1 }}
              exit={{ opacity: 0, scale: 0.95 }}
              className="bg-white rounded-2xl p-6 w-full max-w-lg shadow-xl"
              onClick={(e) => e.stopPropagation()}
            >
              <div className="flex items-center justify-between mb-6">
                <h3 className="text-xl font-bold text-[#111827]">Register a guest</h3>
                <button onClick={() => setShowModal(false)} className="p-1.5 rounded-lg text-[#6B7280] hover:bg-[#F5F6FA]">
                  <X className="w-5 h-5" />
                </button>
              </div>

              <div className="space-y-4">
                {/* Sponsor autocomplete */}
                <div>
                  <label className="block text-sm font-medium text-[#6B7280] mb-1">Sponsor member</label>
                  <input
                    type="text"
                    placeholder="Search member…"
                    value={sponsorSearch}
                    onChange={(e) => setSponsorSearch(e.target.value)}
                    className={inputClass}
                  />
                  {sponsorSearch && filteredMembers.length > 0 && (
                    <div className="mt-1 bg-white border border-[#E0E0E0] rounded-xl shadow-sm overflow-hidden">
                      {filteredMembers.map((m) => (
                        <button
                          key={m.id}
                          onClick={() => {
                            setForm({ ...form, sponsorMemberId: m.id });
                            setSponsorSearch(m.name);
                          }}
                          className={`w-full text-left px-4 py-2.5 text-sm hover:bg-[#F8FAFF] transition-colors ${
                            form.sponsorMemberId === m.id ? "font-bold text-[#4880FF]" : "text-[#111827]"
                          }`}
                        >
                          {m.name}
                        </button>
                      ))}
                    </div>
                  )}
                </div>

                <div className="grid grid-cols-2 gap-4">
                  <div>
                    <label className="block text-sm font-medium text-[#6B7280] mb-1">First name</label>
                    <input className={inputClass} value={form.firstName}
                      onChange={(e) => setForm({ ...form, firstName: e.target.value })}
                      placeholder="Alice" />
                  </div>
                  <div>
                    <label className="block text-sm font-medium text-[#6B7280] mb-1">Last name</label>
                    <input className={inputClass} value={form.lastName}
                      onChange={(e) => setForm({ ...form, lastName: e.target.value })}
                      placeholder="Fontaine" />
                  </div>
                </div>

                <div className="grid grid-cols-2 gap-4">
                  <div>
                    <label className="block text-sm font-medium text-[#6B7280] mb-1">Date of birth</label>
                    <input className={inputClass} type="date" value={form.dateOfBirth}
                      onChange={(e) => setForm({ ...form, dateOfBirth: e.target.value })} />
                  </div>
                  <div>
                    <label className="block text-sm font-medium text-[#6B7280] mb-1">Email</label>
                    <input className={inputClass} type="email" value={form.email}
                      onChange={(e) => setForm({ ...form, email: e.target.value })}
                      placeholder="alice@email.com" />
                  </div>
                </div>
              </div>

              <div className="flex gap-3 mt-8">
                <button onClick={() => setShowModal(false)} className="flex-1 py-2.5 bg-[#F5F6FA] text-[#6B7280] font-semibold rounded-xl hover:bg-[#E0E0E0] transition-colors">Cancel</button>
                <button onClick={handleCreate} className="flex-1 py-2.5 bg-[#4880FF] text-white font-semibold rounded-xl hover:bg-[#3b6ee0] transition-colors flex items-center justify-center gap-2">
                  <Check className="w-4 h-4" /> Register guest
                </button>
              </div>
            </motion.div>
          </motion.div>
        )}

        {/* Ban Confirm Modal */}
        {showBanConfirm && (
          <motion.div
            initial={{ opacity: 0 }}
            animate={{ opacity: 1 }}
            exit={{ opacity: 0 }}
            className="fixed inset-0 bg-black/40 backdrop-blur-sm z-50 flex items-center justify-center p-4"
            onClick={() => setShowBanConfirm(null)}
          >
            <motion.div
              initial={{ opacity: 0, scale: 0.95 }}
              animate={{ opacity: 1, scale: 1 }}
              exit={{ opacity: 0, scale: 0.95 }}
              className="bg-white rounded-2xl p-6 w-full max-w-sm shadow-xl"
              onClick={(e) => e.stopPropagation()}
            >
              <div className="flex items-center gap-3 mb-4">
                <div className="w-10 h-10 rounded-xl bg-[#FFF0F0] flex items-center justify-center">
                  <ShieldAlert className="w-5 h-5 text-[#FF4747]" />
                </div>
                <h3 className="text-lg font-bold text-[#111827]">Ban this guest?</h3>
              </div>
              <p className="text-sm text-[#6B7280] mb-6">
                <span className="font-bold text-[#111827]">{showBanConfirm.firstName} {showBanConfirm.lastName}</span>{" "}
                will be permanently banned and denied access to all clubs.
              </p>
              <div className="flex gap-3">
                <button onClick={() => setShowBanConfirm(null)} className="flex-1 py-2.5 bg-[#F5F6FA] text-[#6B7280] font-semibold rounded-xl hover:bg-[#E0E0E0] transition-colors">Cancel</button>
                <button onClick={() => handleBan(showBanConfirm)} className="flex-1 py-2.5 bg-[#FF4747] text-white font-semibold rounded-xl hover:bg-[#e03d3d] transition-colors flex items-center justify-center gap-2">
                  <ShieldAlert className="w-4 h-4" /> Confirm ban
                </button>
              </div>
            </motion.div>
          </motion.div>
        )}
      </AnimatePresence>
    </div>
  );
}
